cmake_minimum_required(VERSION 3.10)

configure_file(${CMAKE_SOURCE_DIR}/CMake/config.h.in
	       ${CMAKE_CURRENT_BINARY_DIR}/config.h)
add_subdirectory(lib)
add_subdirectory(bg)
add_subdirectory(cfg)
add_subdirectory(ctrl)
add_subdirectory(dialog)
if (PEKWM_HAVE_PAM)
	add_subdirectory(lock)
endif (PEKWM_HAVE_PAM)
add_subdirectory(panel)
add_subdirectory(sys)
add_subdirectory(tk)
if (PEKWM_HAVE_IMAGE_PNG)
	add_subdirectory(screenshot)
endif (PEKWM_HAVE_IMAGE_PNG)
add_subdirectory(wm)
