#!/bin/sh

cat << EOF
APM version: 1.2
APM Management: Disabled
AC Line status: on-line
Battery Status: charging
Remaining battery life: 86%
Remaining battery time: unknown
Number of batteries: 1
Battery 0:
	Battery Status: charging
	Remaining battery life: 86%
	Remaining battery time: unknown
Resume timer: Tue Nov 30 00:00:00 -001
Resume on ring indicator: disabled
EOF
