#!/bin/sh

cat << EOF
APM version: 1.2
APM Management: Disabled
AC Line status: on-line
Battery Status: charging
Remaining battery life: unknown
Remaining battery time: unknown
Number of batteries: 0
Resume timer: Tue Nov 30 00:17:30 -001
Resume on ring indicator: disabled
EOF
